### ISSUE TITLE
issue on wmsImageLayer.cs

### ISSUE THREAD

**Issue by injektilo70** [ClemensFischer/XAML-Map-Control#3]
First of all thanks a lot Clemens for your magnificent work.
Using wms layers i've noticed that in case of wms services that includes a "?", like this service:
`http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Corine_Land_Cover2012_IVliv.map&`, 
the statement
`var uri = new Uri(ServerUri, query.Replace(" ", "%20"));`
changes abnormally the original uri address like this:
`http://wms.pcn.minambiente.it/&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=CS.CLC.2012&STYLES=&CRS=EPSG:3857&BBOX=-533469.3125,4043161.5,3539095.4375,6129586.5&WIDTH=1665&HEIGHT=853&FORMAT=image/png&TRANSPARENT=FALSE`
Best regards,
F.

**Comment by ClemensFischer** [comment]
Thanks for catching that. Fixed in current release 3.4.1.

**Comment by injektilo70** [comment]
Sorry Clemens,
just for your information, the problem is still present.
To make it work, I replaced this piece of code

```
if (!uri.EndsWith("?") && !uri.EndsWith("&"))
{
     uri += "?";
}
```
with this one:

```
if(uri.Contains("?"))
{
    uri += "&";
}
else if (uri.Contains("&"))
{
    uri += "?";
}
```

Best regards,
F.

**Comment by ClemensFischer** [comment]
I have explicitly not done it that way, and successfully tested your service with the current release. Just make sure your ServerUri actually ends with `&` to signal that there already are query parameters present.

You may perhaps also have set `ServerUri = new Uri("http://wms.pcn.minambiente.it/ogc")` and `Parameters="map=/ms_ogc/WMS_v1.3/Vettoriali/Corine_Land_Cover2012_IVliv.ma"`.
